// Auto-generated by mcp__supabase__generate_typescript_types against the
// live project schema (supabase/migrations/0001 + 0002). Regenerate after
// any schema change — do not hand-edit.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      chat_messages: {
        Row: {
          body: string;
          created_at: string;
          id: string;
          read_at: string | null;
          sender_id: string;
          sender_role: string;
          thread_id: string;
        };
        Insert: {
          body: string;
          created_at?: string;
          id?: string;
          read_at?: string | null;
          sender_id: string;
          sender_role: string;
          thread_id: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          id?: string;
          read_at?: string | null;
          sender_id?: string;
          sender_role?: string;
          thread_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chat_messages_sender_id_fkey";
            columns: ["sender_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_messages_thread_id_fkey";
            columns: ["thread_id"];
            isOneToOne: false;
            referencedRelation: "chat_threads";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_threads: {
        Row: {
          client_id: string;
          created_at: string;
          id: string;
          last_message_at: string | null;
        };
        Insert: {
          client_id: string;
          created_at?: string;
          id?: string;
          last_message_at?: string | null;
        };
        Update: {
          client_id?: string;
          created_at?: string;
          id?: string;
          last_message_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "chat_threads_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      client_assets: {
        Row: {
          client_id: string;
          created_at: string;
          created_by: string | null;
          description: string | null;
          id: string;
          kind: string;
          secret_value: string | null;
          storage_path: string | null;
          title: string;
          url: string | null;
        };
        Insert: {
          client_id: string;
          created_at?: string;
          created_by?: string | null;
          description?: string | null;
          id?: string;
          kind: string;
          secret_value?: string | null;
          storage_path?: string | null;
          title: string;
          url?: string | null;
        };
        Update: {
          client_id?: string;
          created_at?: string;
          created_by?: string | null;
          description?: string | null;
          id?: string;
          kind?: string;
          secret_value?: string | null;
          storage_path?: string | null;
          title?: string;
          url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "client_assets_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "client_assets_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      client_plans: {
        Row: {
          base_price_paise: number;
          client_id: string;
          created_at: string;
          created_by: string | null;
          custom_addons: Json;
          ended_at: string | null;
          id: string;
          notes: string | null;
          plan_key: string;
          plan_name: string;
          started_at: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          base_price_paise: number;
          client_id: string;
          created_at?: string;
          created_by?: string | null;
          custom_addons?: Json;
          ended_at?: string | null;
          id?: string;
          notes?: string | null;
          plan_key: string;
          plan_name: string;
          started_at?: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          base_price_paise?: number;
          client_id?: string;
          created_at?: string;
          created_by?: string | null;
          custom_addons?: Json;
          ended_at?: string | null;
          id?: string;
          notes?: string | null;
          plan_key?: string;
          plan_name?: string;
          started_at?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "client_plans_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "client_plans_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      domain_status: {
        Row: {
          auto_renew: boolean;
          client_id: string;
          created_at: string;
          domain_name: string;
          id: string;
          notes: string | null;
          purchased_at: string | null;
          registrar: string | null;
          renewal_date: string | null;
          status: string;
          updated_at: string;
        };
        Insert: {
          auto_renew?: boolean;
          client_id: string;
          created_at?: string;
          domain_name: string;
          id?: string;
          notes?: string | null;
          purchased_at?: string | null;
          registrar?: string | null;
          renewal_date?: string | null;
          status?: string;
          updated_at?: string;
        };
        Update: {
          auto_renew?: boolean;
          client_id?: string;
          created_at?: string;
          domain_name?: string;
          id?: string;
          notes?: string | null;
          purchased_at?: string | null;
          registrar?: string | null;
          renewal_date?: string | null;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "domain_status_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          amount_paise: number;
          client_id: string;
          client_plan_id: string | null;
          created_at: string;
          created_by: string | null;
          currency: string;
          description: string;
          id: string;
          line_items: Json;
          paid_at: string | null;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_signature: string | null;
          receipt: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          amount_paise: number;
          client_id: string;
          client_plan_id?: string | null;
          created_at?: string;
          created_by?: string | null;
          currency?: string;
          description: string;
          id?: string;
          line_items?: Json;
          paid_at?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          receipt: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          amount_paise?: number;
          client_id?: string;
          client_plan_id?: string | null;
          created_at?: string;
          created_by?: string | null;
          currency?: string;
          description?: string;
          id?: string;
          line_items?: Json;
          paid_at?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          receipt?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_client_plan_id_fkey";
            columns: ["client_plan_id"];
            isOneToOne: false;
            referencedRelation: "client_plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      payment_events: {
        Row: {
          dedupe_key: string;
          event_type: string;
          id: string;
          order_id: string;
          raw_payload: Json;
          received_at: string;
        };
        Insert: {
          dedupe_key: string;
          event_type: string;
          id?: string;
          order_id: string;
          raw_payload: Json;
          received_at?: string;
        };
        Update: {
          dedupe_key?: string;
          event_type?: string;
          id?: string;
          order_id?: string;
          raw_payload?: Json;
          received_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payment_events_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          company_name: string | null;
          created_at: string;
          full_name: string | null;
          id: string;
          is_admin: boolean;
          phone: string | null;
          updated_at: string;
        };
        Insert: {
          company_name?: string | null;
          created_at?: string;
          full_name?: string | null;
          id: string;
          is_admin?: boolean;
          phone?: string | null;
          updated_at?: string;
        };
        Update: {
          company_name?: string | null;
          created_at?: string;
          full_name?: string | null;
          id?: string;
          is_admin?: boolean;
          phone?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      is_admin: { Args: never; Returns: boolean };
      mark_thread_read: { Args: { p_thread_id: string }; Returns: undefined };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
