export const plans = {
  eyebrow: "Plans",
  title: "Simple Plans For Serious Growth",
  lede: "Choose the perfect plan for your business and grow your online presence with confidence.",
  footnote: "Final price will be decided after a discussion with your designer.",
  // "Gold" is flagged Most Popular — the middle tier most clients land on
  // once they've compared page count against support length.
  popular: "Gold",
  tiers: [
    {
      name: "Plan A",
      tag: "Bronze",
      icon: "🚀",
      price: "₹6,999",
      priceNote: "(MRP)",
      features: [
        "Up to 5 unique pages",
        "Mobile responsive",
        "Basic SEO",
        "Contact form",
        "Social media links",
        "Google Map integration",
        "3 days support",
        "Maintenance fee (excluding)",
      ],
    },
    {
      name: "Plan B",
      tag: "Silver",
      icon: "💎",
      price: "₹10,000",
      priceNote: "(MRP)",
      features: [
        "Up to 7 unique pages",
        "Mobile responsive",
        "On-page SEO",
        "Contact form",
        "Social media links",
        "Google Map integration",
        "WhatsApp integration",
        "Blog section",
        "7 days support",
        "Maintenance fee (excluding)",
      ],
    },
    {
      name: "Plan C",
      tag: "Gold",
      icon: "👑",
      price: "₹21,000",
      priceNote: "(MRP)",
      features: [
        "Up to 10 unique pages",
        "Mobile responsive",
        "Advanced SEO",
        "Contact form",
        "Social media links",
        "Google Map integration",
        "WhatsApp integration",
        "Blog section",
        "1 month support",
        "Maintenance fee (excluding)",
      ],
    },
    {
      name: "Plan D",
      tag: "Platinum",
      icon: "⭐",
      price: "₹40,000",
      priceNote: "(MRP)",
      features: [
        "Up to 15 unique pages",
        "Mobile responsive",
        "Advanced SEO",
        "Contact form",
        "Social media links",
        "Google Map integration",
        "WhatsApp integration",
        "Blog section",
        "2 months support",
        "Maintenance fee (excluding)",
      ],
    },
    {
      name: "Plan E",
      tag: "Diamond",
      icon: "👑",
      price: "₹70,000",
      priceNote: "(MRP)",
      features: [
        "Up to 10 unique pages",
        "Mobile responsive",
        "Advanced SEO",
        "Contact form",
        "Social media links",
        "Google Map integration",
        "WhatsApp integration",
        "Blog section",
        "Gallery / portfolio",
        "Live chat integration",
        "Priority support",
        "12 months support",
      ],
    },
  ],
};
